version: '3.1'

services:
    mongodb:
        container_name: automation-mongo
        image: mongo
        ports:
            - 27027:27017
        volumes:
            - mongodb:/data/db

networks:
    automation-network:
        driver: bridge
volumes:
    mongodb:
        driver: local
